Parameters:
  DBInstanceID:
    Default: mydbinstance
    Description: My database instance
    Type: String
    MinLength: '1'
    MaxLength: '63'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: >-
      Must begin with a letter and must not end with a hyphen or contain two
      consecutive hyphens.
  DBName:
    Default: mydb
    Description: My database
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: Must begin with a letter and contain only alphanumeric characters.
  DBInstanceClass:
    Default: db.m5.large
    Description: DB instance class
    Type: String
    ConstraintDescription: Must select a valid DB instance type.
  DBAllocatedStorage:
    Default: '50'
    Description: The size of the database (GiB)
    Type: Number
    MinValue: '20'
    MaxValue: '65536'
  DBPort:
    Default: '5432'
    Description: DB default port
    Type: Number
    MinValue: '1024'
    MaxValue: '65536'
    ConstraintDescription: must be between 20 and 65536 GiB.
  DBUsername:
    NoEcho: 'true'
    Description: Username for database access
    Type: String
    MinLength: '1'
    MaxLength: '16'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: 'true'
    Description: Password database access
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: '[a-zA-Z0-9]*'
  DBSubnetId1:
    Description: Subnet id to deploy in
    Type: String
  DBSubnetId2:
    Description: Subnet id to deploy in
    Type: String
  PublicSubnetId:
    Description: Subnet id to deploy bastion in
    Type: String
  VPCId:
    Description: VPC id to deploy in
    Type: String
  CidrForDbAccess:
    NoEcho: 'true'
    Description: network mask of hosts allowed to access DB
    Type: String
    AllowedPattern: '((\d{1,3})\.){3}\d{1,3}/\d{1,2}'
    Default: 10.50.0.0/16
  IsPublic:
    Description: Is this DB publicly accessible?
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  IsProtected:
    Description: create with deletion protection
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  IsMultiAZ:
    Description: is it multi az deployment
    Type: String
    Default: 'false'
    AllowedValues:
    - 'true'
    - 'false'
  DBEngine:
    Type: String
  DBEngineVersion:
    Type: Number
  RestoreRoleArn:
    Type:String
  EC2InstanceType:
    Type: String
    Default: t2.micro
  EC2AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  KeyName:
    Type: String
    
    
Resources:
  
  OptionGroup:
    Type: 'AWS::RDS::OptionGroup'
    Properties: 
        EngineName: !Ref DBEngine
        MajorEngineVersion: !Ref DBEngineVersion
        OptionConfigurations: 
            - OptionName: SQLSERVER_BACKUP_RESTORE
              OptionSettings:
            - Name: IAM_ROLE_ARN
              Value: 'arn:aws:iam::333333333333333:role/service-role/sqlserverrestore' 
  
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VPCId
      GroupDescription: Access DB from VPC only
      SecurityGroupIngress:
      - IpProtocol: TCP
        FromPort: !Ref DBPort
        ToPort: !Ref DBPort
        CidrIp: !Ref CidrForDbAccess
        
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: "DBSubnetGroup For Deployment"
      SubnetIds:
        - !Ref DBSubnetId1
        - !Ref DBSubnetId2
  
  DBInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceID
      DBName: !Ref DBName
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: !Ref DBAllocatedStorage
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      LicenseModel: license-included
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      PubliclyAccessible: !Ref IsPublic
      StorageType: standard
#      StorageEncrypted: true
 #     KmsKeyId: KeyName
      DeletionProtection: !Ref IsProtected
      VPCSecurityGroups: [!Ref DBSecurityGroup]
      MultiAZ: !Ref IsMultiAZ
      DBSubnetGroupName: !Ref DBSubnetGroup
      OptionGroupName: !Ref OptionGroup
   
  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref EC2AMI
      InstanceType: !Ref EC2InstanceType
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-BastionInstance'

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        !Sub 'Security group for ${AWS::StackName} bastion host'
      VpcId: !Ref VPC

  BastionAllowInboundSSHFromInternet:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref BastionSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0

  BastionAllowOutboundSSHToApplication:
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      GroupId: !Ref BastionSecurityGroup
      IpProtocol: tcp
      FromPort: !Ref  DBPort
      ToPort: !Ref DBPort
      CidrIp: 0.0.0.0/0
 
Outputs:
  Endpoint:
      Value: !GetAtt 'DBInstance.Endpoint.Address'
  BastionPublicIp:
      Description: 'Bastion Public IP'
      Value: !Sub 'http://${BastionInstance.PublicIp}'